/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package temporizador2;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Portátil
 */
public class Temporizador2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Temporizador2() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        minutos = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        desactivar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temporizador");
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Introduce los minutos restantes para que se apague el PC");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 0, 330, 29);

        minutos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        minutos.setText("Tiempo en minutos");
        minutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minutosMouseClicked(evt);
            }
        });
        minutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutosActionPerformed(evt);
            }
        });
        getContentPane().add(minutos);
        minutos.setBounds(200, 150, 130, 30);

        aceptar.setText("Aceptar");
        aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarMouseClicked(evt);
            }
        });
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(340, 150, 73, 30);

        desactivar.setText("Desactivar apagado");
        desactivar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desactivarMouseClicked(evt);
            }
        });
        desactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desactivarActionPerformed(evt);
            }
        });
        getContentPane().add(desactivar);
        desactivar.setBounds(270, 200, 140, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/temporizador/fondo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 430, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarActionPerformed

    private void minutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minutosActionPerformed

    private void minutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minutosMouseClicked
        // TODO add your handling code here:
        minutos.setText("");
    }//GEN-LAST:event_minutosMouseClicked

    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icono.png")));
    }
    
    private void aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseClicked
        // TODO add your handling code here:
        if(!"".equals(minutos.getText())&&!"Tiempo en minutos".equals(minutos.getText())){
            Apagado fin = new Apagado();
            try{
                fin.temporizador(Integer.parseInt(minutos.getText()));
                JOptionPane.showMessageDialog(null, "El quipo se apagará en "+minutos.getText()+" minutos, ya puede cerrar la ventana", "Temporizador activado", HEIGHT);
            } catch (Exception e){
                minutos.setText("");
                JOptionPane.showMessageDialog(null, "Escribe el tiempo en minutos. Ej: '60' y pulsa aceptar", "ERROR", HEIGHT);

            }
           
        }
    }//GEN-LAST:event_aceptarMouseClicked

    private void desactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactivarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desactivarActionPerformed

    private void desactivarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desactivarMouseClicked
        // TODO add your handling code here:
        new Apagado().desactivar();
    }//GEN-LAST:event_desactivarMouseClicked

        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temporizador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temporizador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temporizador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temporizador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temporizador2().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton desactivar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField minutos;
    // End of variables declaration//GEN-END:variables
}
